### ISSUE TITLE
Program doesn't work for all the cases

### ISSUE THREAD

**Issue by NarayanHasyagar** [srtbhat/SSCD_LAB#1]
Program cant find and replace if the input string is a substring within a string.

**Comment by apoc146** [comment]
Which all?

**Comment by DOJI45** [comment]
Thanks for pointing out bug!!!

Issue is now fixed.

As lex does not support lazy regex matching, we need to manipulate yytext to achieve replacing the string within string (I didn't get any easy method, if you guys get it please share).

For more details look into code - LEX - program7a.l

Thank you
